- id: npm-lint
  name: npm-lint
  entry: lib/run-npm-lint.sh
  language: 'script'
  description: ""
- id: npm-test
  name: npm-test
  entry: lib/run-npm-test.sh
  language: 'script'
  description: ""
